"""Verification and rewriting layer.

Three jobs, all implemented deterministically so the prototype runs end to end
with zero external services or API keys:

  * generate() — stand in for the upstream model that Sentinel proxies
  * judge()    — the Performance lane's verifier (grounding-based scoring)
  * repair()   — regenerate a grounded answer during Auto-repair

The judge and repair steps are deliberately isolated behind this module so a
real LLM endpoint can be plugged in later without touching the control plane.
"""
from __future__ import annotations

import re
import time
from typing import Any

from .models import ModelResponse


def _approx_tokens(text: str) -> int:
    return max(1, round(len(text) / 4))


class Verifier:
    online = False  # kept for callers that check; this build is fully self-contained

    # ------------------------------------------------------------------ upstream
    def generate(self, system: str, prompt: str, history: list[dict[str, str]] | None = None,
                 max_tokens: int = 700) -> ModelResponse:
        t0 = time.perf_counter()
        text = (
            "Thanks for reaching out. Based on our policy, "
            f"here is a general answer to: {prompt.strip()[:160]}"
        )
        return ModelResponse(
            text=text, model="builtin-stub",
            prompt_tokens=_approx_tokens(system + prompt),
            completion_tokens=_approx_tokens(text),
            latency_ms=(time.perf_counter() - t0) * 1000,
        )

    # --------------------------------------------------------------------- judge
    def judge(self, question: str, answer: str, context: str,
              offline_grounding: float, confident_language: bool) -> dict[str, Any]:
        grounding = offline_grounding
        factuality = round(0.5 + 0.45 * grounding, 3)
        groundedness = round(grounding, 3)
        calibration = 0.9 if not confident_language else round(min(1.0, grounding + 0.15), 3)
        if grounding < 0.3:
            verdict = "fabricated" if not context else "partially_unsupported"
        elif grounding < 0.45:
            verdict = "partially_unsupported"
        else:
            verdict = "ok"
        if confident_language and grounding < 0.55:
            calibration = round(grounding * 0.5, 3)
        return {
            "factuality": factuality, "groundedness": groundedness,
            "calibration": calibration, "verdict": verdict,
            "unsupported_claims": [], "rationale": "grounding-based verifier",
            "engine": "deterministic",
        }

    # -------------------------------------------------------------------- repair
    def repair(self, question: str, answer: str, context: str, issues: list[str]) -> ModelResponse:
        t0 = time.perf_counter()
        # Keep only sentences that (a) overlap the source context and
        # (b) contain no figure that is absent from the context.
        from .retrieval import tokenize

        num_unit = re.compile(
            r"(?<![\d,])(\d+(?:\.\d+)?)(?:[\s-]+[a-z]+){0,3}?[\s-]?"
            r"(%|percent|eur|usd|days?|weeks?|months?|years?|hours?)", re.I)
        ctx_low = context.lower()
        ctx_tokens = set(tokenize(context))
        kept = []
        for sent in re.split(r"(?<=[.!?])\s+", answer.strip()):
            st = set(tokenize(sent))
            if not st:
                continue
            overlap = len(st & ctx_tokens) / len(st)
            nums_ok = all(f"{v}" in ctx_low for v, _ in num_unit.findall(sent))
            if overlap >= 0.34 and nums_ok:
                kept.append(sent)
        text = " ".join(kept).strip() or (
            "I don't have a source-backed answer to that. Please check with a human specialist."
        )
        text += " (Regenerated by Sentinel against verified sources.)"
        return ModelResponse(
            text=text, model="builtin-repair",
            prompt_tokens=_approx_tokens(answer + context),
            completion_tokens=_approx_tokens(text),
            latency_ms=(time.perf_counter() - t0) * 1000,
        )


llm = Verifier()
